status-response: "ok"
server:
  # Do not remove or disable the following server options for http, ssl, and jks.
  # These values are required because the application load balancer used in
  # Prebid-Server-On-AWS routes incoming requests over SSL on port 8443.
  http:
    enabled: true
    port: 8443
  ssl: true
  jks-path: ${SSL_KEYSTORE_PATH}
  jks-password: ${SSL_KEYSTORE_PASS}
adapters:
  appnexus:
    enabled: true
  ix:
    enabled: true
  openx:
    enabled: true
  pubmatic:
    enabled: true
  rubicon:
    enabled: true
metrics:
  logback:
    enabled: true
    name: METRICS
    interval: 30
cache:
  scheme: http
  host: ${CACHE_HOST}
  path: /cache
  query: uuid=
settings:
  enforce-valid-account: false
  generate-storedrequest-bidrequest-id: true
  s3:
    # These values are loaded from environment variables in the ECS task,
    # as indicated below:
    # access-key-id: <-- AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
    # secret-access-key: <-- AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
    # endpoint: <-- SETTINGS_S3_ENDPOINT
    # bucket: <-- SETTINGS_S3_BUCKET
    # region: <-- SETTINGS_S3_REGION
    accounts-dir: stored_accounts
    stored-imps-dir: stored_impressions
    stored-requests-dir: stored_requests
    stored-responses-dir: stored_responses
  in-memory-cache:
    cache-size: 10000
    ttl-seconds: 1200 # 20 minutes
    s3-update:
      refresh-rate: 900000 # Refresh every 15 minutes
      timeout: 5000
gdpr:
  default-value: 1
  vendorlist:
    v2:
      cache-dir: /var/tmp/vendor2
    v3:
      cache-dir: /var/tmp/vendor3
admin-endpoints:
  logging-changelevel:
    enabled: true
    path: /logging/changelevel
    on-application-port: true
    protected: false
analytics:
  global:
    adapters: "psdoaAnalytics"
  psdoa:
    enabled: false
